**1. Creating NumPy Arrays**

### **Complete Theoretical Explanation of NumPy Arrays**

#### **1. Creating NumPy Arrays**
NumPy arrays can be created in multiple ways. The simplest method is converting Python lists into NumPy arrays. Unlike Python lists, NumPy arrays require all elements to have the same data type, which allows for **faster processing and optimized memory usage**.

Additionally, NumPy provides built-in methods to create arrays from scratch:
- **Zero-filled arrays:** Useful for initializing matrices before computation.
- **One-filled arrays:** Frequently used in neural networks and default structures.
- **Custom value-filled arrays:** Enables specific initialization of array contents.
- **Identity matrices:** Essential for linear algebra operations.
- **Range-based arrays:** Generates sequences efficiently.
- **Linearly spaced arrays:** Useful for interpolations and numerical methods.

These shortcuts prevent unnecessary looping in Python, improving computational efficiency.

---

#### **2. Checking Array Properties**
NumPy arrays come with metadata that provides detailed insights into their structure:
- **Shape:** Defines the number of rows and columns, making multi-dimensional manipulations possible.
- **Size:** Represents the total number of elements.
- **Dimensions:** Distinguishes between 1D, 2D, and higher-dimensional arrays.
- **Data Type:** Ensures uniformity, avoiding Python’s dynamic type overhead.

By knowing these properties, developers can optimize array operations for better efficiency and memory usage.

---

#### **3. Changing Data Types**
NumPy arrays allow explicit specification of data types upon creation. This ensures **efficient memory consumption** and **precision control**. Data type conversion can be performed when transitioning between integer and float representations. Choosing the right data type is crucial in numerical computing, as it impacts both **performance and storage requirements**.

---

#### **4. Reshaping and Flattening Arrays**
Reshaping allows transforming arrays from one dimensionality to another while retaining all elements. This is fundamental for applications like **machine learning**, where data needs to be reshaped for model compatibility. 

Flattening simplifies a multi-dimensional array into a **single list-like structure**, making it easier to process datasets in linear form.

---

### **Key Takeaways**
- NumPy arrays are **faster** than lists due to homogeneous data storage.
- Various creation methods help eliminate unnecessary loops.
- Understanding **shape, size, and dimensionality** improves performance optimization.
- **Data type selection** impacts both speed and memory efficiency.
- Reshaping and flattening are crucial for manipulating structured datasets.

Since you're deeply engaged with numerical computing, exploring **advanced NumPy features like broadcasting and memory profiling** could be a great next step! 🚀 Let me know if you'd like a detailed breakdown.

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [7]:
np.zeros([3,4])
np.ones([3,4])


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.full((2,2),9)

array([[9, 9],
       [9, 9]])

In [12]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
np.arange(1,100,9)##1,1+9,19+10.........100

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [15]:
np.linspace(1,100,5)##equal space  array

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [23]:
arry=np.array([[1,2,3],[4,5,6],[7,8,9]])##list of list so 2d
print(arry)
print(arry.shape)
print(arry.size)
print(arry.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
2


In [24]:
arry.dtype##default

dtype('int32')

In [29]:
arry=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='float')
print(arry)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [30]:
arry.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [31]:
arry.shape

(3, 3)

In [34]:
reshape=arry.reshape((3,3))