### Built-in Mathematical Functions in NumPy

NumPy provides a set of powerful built-in functions that help in performing mathematical and statistical operations on arrays efficiently. These functions leverage optimized C-based operations, making them faster and more memory-efficient than traditional Python loops. Here are some commonly used NumPy methods for mathematical computations:

1. **`np.mean()`** – This function computes the mean (average) of an array. It is commonly used to find the central tendency of a dataset.

   * **Usage**: Calculates the sum of all elements in the array and divides it by the number of elements.

2. **`np.std()`** – Computes the standard deviation of an array, which measures the spread of data points from the mean.

   * **Usage**: Standard deviation is a common measure of variability or dispersion in a dataset.

3. **`np.var()`** – Calculates the variance of an array, which is the square of the standard deviation. Variance helps understand the degree of spread in a dataset.

   * **Usage**: It indicates how far the data points are spread out from the mean.

4. **`np.min()`** – Returns the minimum value in the array.

   * **Usage**: Helpful in finding the smallest element in a dataset.

5. **`np.max()`** – Returns the maximum value in the array.

   * **Usage**: Used to find the largest element in a dataset.

6. **`np.sum()`** – Computes the sum of all elements in the array.

   * **Usage**: Useful when you need to get the total sum of all values.

7. **`np.prod()`** – Calculates the product of all elements in an array.

   * **Usage**: This can be useful for finding the cumulative product of a series of numbers.

8. **`np.median()`** – Finds the median of an array, which is the middle value when the elements are sorted.

   * **Usage**: The median is a robust measure of central tendency, less affected by outliers than the mean.

9. **`np.percentile()`** – Computes the percentile of an array, which gives the value below which a given percentage of observations fall.

   * **Usage**: Commonly used in statistical analysis, especially in understanding the distribution of data.

10. **`np.argmin()`** – Returns the index of the minimum value in an array.

    * **Usage**: This function helps identify where the smallest element is located within an array.

11. **`np.argmax()`** – Returns the index of the maximum value in an array.

    * **Usage**: Similar to `argmin()`, this function helps identify the position of the largest element in an array.

12. **`np.corrcoef()`** – Computes the correlation coefficient matrix of two arrays, which helps to understand the relationship between them.

    * **Usage**: It is often used in statistics and machine learning to determine how closely related two datasets are.

13. **`np.unique()`** – Finds and returns the unique elements in an array.

    * **Usage**: Used to identify distinct values in a dataset, useful in data preprocessing and analysis.

14. **`np.diff()`** – Computes the differences between consecutive elements of an array.

    * **Usage**: This can be helpful when analyzing changes or trends in a dataset, such as the rate of change.

15. **`np.cumsum()`** – Computes the cumulative sum of an array, providing a running total of the elements.

    * **Usage**: Useful in time-series analysis or when tracking cumulative data over time.

16. **`np.linspace()`** – Creates an array with evenly spaced numbers over a specified interval.

    * **Usage**: Often used to generate data points for graphs, simulations, or experiments with fixed intervals.

17. **`np.log()`** – Computes the natural logarithm of each element in the array.

    * **Usage**: The natural logarithm is widely used in various fields, including data analysis, finance, and science.

18. **`np.exp()`** – Computes the exponential of each element in the array.

    * **Usage**: The exponential function is crucial in many mathematical models, such as growth and decay processes.

These built-in functions enhance performance and simplify code for handling large arrays in scientific, engineering, and machine learning tasks. They provide an efficient way to perform common mathematical and statistical operations without resorting to slow Python loops.


In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])

In [3]:
np.mean(arr)

2.5

In [4]:
np.std(arr)

1.118033988749895

In [5]:
np.var(arr)

1.25

In [6]:
np.min(arr)

1

In [7]:
np.sum(arr)

10

In [8]:
np.prod(arr)

24

In [9]:
np.median(arr)

2.5

In [10]:
np.percentile(arr, 50)  # For the 50th percentile (median)

2.5

In [11]:
np.argmin(arr)##index with smallest 

0

In [12]:
np.argmax(arr)

3

In [15]:
np.diff(arr)

array([1, 1, 1])

In [14]:
np.unique(arr)##no duplicate

array([1, 2, 3, 4])

In [16]:
np.cumsum(arr)

array([ 1,  3,  6, 10])

In [20]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10In this example, the array is created with 5 evenly spaced numbers between 0 and 10, including both endpoints (0 and 10). The spacing between consecutive numbers is 2.5.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [19]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])