

---

## 📌 Indexing and Slicing in NumPy

### 🔹 Indexing

Indexing in NumPy works similarly to Python lists. You can access individual elements of a NumPy array using their index positions. Positive indices access from the beginning, while negative indices count from the end of the array.

### 🔹 Slicing

Slicing refers to extracting a portion or subset of an array using a start\:stop\:step syntax. It allows you to extract specific ranges or patterns of elements.

* **Start**: The index to begin the slice (inclusive).
* **Stop**: The index to stop (exclusive).
* **Step**: The interval between elements.

### ⚠️ Important: Slicing Returns a View, Not a Copy

Unlike Python lists, slicing a NumPy array does **not** create a new array—it returns a **view** of the original array. This means that changes made to the sliced array will directly reflect in the original array.

#### Why does slicing return a view in NumPy?

* **Memory Efficiency**: Prevents unnecessary duplication of data, which is especially beneficial for large datasets.
* **Performance**: Enables fast manipulation and access without allocating additional memory.

If an independent copy is required, the `.copy()` method should be used to avoid altering the original data.

---

## 🔸 Fancy Indexing & Boolean Masking

### ✅ Fancy Indexing

Fancy indexing lets you access multiple elements of an array at once by passing a list or array of specific indices. This is useful when you need non-contiguous or specifically selected elements.

### ✅ Boolean Masking

Boolean masking is a powerful feature that allows filtering of data using boolean conditions. A boolean array (mask) is created by applying a condition, and this mask is used to extract elements that meet the condition.

Boolean masking is highly efficient and is commonly used for filtering and conditional data operations in large datasets.

---

## 📝 Summary

* NumPy arrays provide a faster, memory-efficient alternative to Python lists.
* Arrays can be created using various functions like `np.array()`, `np.zeros()`, `np.ones()`, and more.
* Indexing and slicing allow direct and flexible access to array data.
* Slicing returns a **view**, not a **copy**, which shares memory with the original array.
* Use `.copy()` to create a true duplicate of an array slice.
* Fancy indexing and boolean masking provide efficient ways to filter and access data based on custom conditions.
* These operations make NumPy a powerful tool for handling large numerical datasets efficiently.

---

## 🧠 Exercises to Reinforce Learning

1. Describe the shape of a 3×3 array filled with random numbers.
2. Explain how to convert an array of floats into integers.
3. Discuss the use of fancy indexing to extract even numbers from a given array.
4. Outline how to reshape a 1D array into a 3×3 matrix.
5. Describe how to use boolean masking to filter elements greater than a certain value in an array.

---




In [ ]:
**Indexing (Same as Python Lists)**

**Slicing (Extracting Parts of an Array)**

In [9]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [10]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [12]:
flat = arr.flatten()##convert to  1d array

In [13]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [14]:
flat[0]

1

In [15]:
flat[5]

6

In [16]:
flat[3:6]

array([4, 5, 6])

In [19]:
flat[:5]

array([1, 2, 3, 4, 5])

In [20]:
flat[5:]

array([ 6,  7,  8,  9, 11, 12, 13])

In [21]:
print(arr[::2])

[[1 2 3]
 [7 8 9]]


In [22]:
b=flat[3:7]

In [23]:
b

array([4, 5, 6, 7])

In [25]:
b[0]=44444

In [26]:
b##it is a view that is slissing  it is not a copy it will refer the same ass numpy which was there earlier

array([44444,     5,     6,     7])

In [27]:
flat

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          11,    12,    13])

In [32]:
## i want to make the copy so it is not the slicing 
b=flat[3:7].copy()


In [33]:
b

array([44444,     5,     6,     7])

In [34]:
print(b)

[44444     5     6     7]


In [35]:
flat

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          11,    12,    13])

In [36]:
arr=np.array([1,54,23,53,2,3,34,5,6])

In [37]:
arr[[1,4,5]]##fancy indexcing which will tell that at index 1,4,5 which no. is there 

array([54,  2,  3])

In [41]:
##boolean masking
arr[arr>10]

array([54, 23, 53, 34])

**practice question**

In [42]:
random_array = np.random.rand(3, 3)
print("Shape of the random array:", random_array.shape)

Shape of the random array: (3, 3)


In [43]:
float_array = np.array([1.1, 2.2, 3.3])
int_array = float_array.astype(int)
print("Converted integers:", int_array)

Converted integers: [1 2 3]


In [44]:
numbers = np.array([1, 2, 3, 4, 5, 6])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers:", even_numbers)

Even numbers: [2 4 6]


In [45]:
one_d_array = np.arange(9)
reshaped_array = one_d_array.reshape(3, 3)
print("Reshaped matrix:\n", reshaped_array)

Reshaped matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [46]:
values = np.array([10, 55, 30, 75, 45, 90])
filtered_values = values[values > 50]
print("Numbers greater than 50:", filtered_values)

Numbers greater than 50: [55 75 90]
